<?xml version="1.0" encoding="UTF-8" ?>
<testsuites disabled="0" errors="0" failures="1" tests="5" time="0.117">
 <testsuite name="Just to test - 1" timestamp="2021-06-09T14:51:55" hostname="localhost" time="0.117" errors="0" tests="5" skipped="2" disabled="0" failures="1">
  <testcase classname="Just to test - 1" name="TC08: Create A Manufacturing Work Order" time="0.001">
   <skipped message="Temporarily disabled with xit" />
  </testcase>
  <testcase classname="Just to test - 1" name="TC09: Add New Company" time="0.002">
   <skipped message="Temporarily disabled with xit" />
  </testcase>
  <testcase classname="Just to test - 1" name="Test1" time="0.002" />
  <testcase classname="Just to test - 1" name="Test2" time="0.002">
   <failure type="exception" message="Failed: test2 failed"><![CDATA[Error: test2 failed
    at wrappedReject (C:\Users\nhchien\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:100:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
From: Task: Run it("Test2") in control flow
    at UserContext.<anonymous> (C:\Users\nhchien\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\nhchien\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\nhchien\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\nhchien\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\nhchien\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\nhchien\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\nhchien\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\nhchien\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\nhchien\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\nhchien\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
From asynchronous test: 
Error
    at Suite.<anonymous> (D:\Titus\protractor_fw_demo_chien\ui-tests\TestScripts\chientest1.js:51:5)
    at addSpecsToSuite (C:\Users\nhchien\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\nhchien\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\nhchien\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (D:\Titus\protractor_fw_demo_chien\ui-tests\TestScripts\chientest1.js:20:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)]]>
   </failure>
  </testcase>
  <testcase classname="Just to test - 1" name="Test3" time="0.109" />
 </testsuite>
</testsuites>